services:
  db:
    image: postgres:16
    container_name: api_users_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_pass
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

volumes:
  db_data:
